---
name: Lint files

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@7ca369a7b39026826ce13e86443b1bee7766f4f4 # 1.22.54
    secrets: inherit
