---
name: Lint files

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@80e6abe387e3e421c999f8d1db4fbd1c52dace73 # 1.22.68
    secrets: inherit
