---
name: Lint files

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@b83422871eb47977aa142138221aae2f18ff042b # 1.22.31
    secrets: inherit
