---
name: Lint files

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@590c56856a43c909afcc719f44ca96e3c2569b17 # 1.22.53
    secrets: inherit
