---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on: pull_request_target

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_renovate_auto_approve_callable.yml@590c56856a43c909afcc719f44ca96e3c2569b17 # 1.22.53
    secrets: inherit
